### ISSUE TITLE
Bellows fails on initial permit

### ISSUE THREAD

**Issue by frog32** [zigpy/bellows#152] opened 2019-03-18 19:19 UTC
If I try to pair a Xiaomi Mijia temperature sensor I get the following error and it is recocnized as default zigbee device. Once I restart homeassistant it gets recognized as zhaquirks.xiaomi.mija.sensor_ht.Weather which is correct. The issue here is that homeassistant then already created some entities and after a restart creates some more.

```
2019-03-17 11:37:30 INFO (MainThread) [homeassistant.components.zha.api] Permitting joins for 60s
2019-03-17 11:37:38 ERROR (MainThread) [bellows.ezsp] Exception running handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bellows/ezsp.py", line 194, in handle_callback
    handler(*args)
  File "/usr/local/lib/python3.7/site-packages/bellows/zigbee/application.py", line 160, in ezsp_callback_handler
    self._handle_frame(*args)
  File "/usr/local/lib/python3.7/site-packages/bellows/zigbee/application.py", line 181, in _handle_frame
    tsn, command_id, is_reply, args = self.deserialize(device, aps_frame.sourceEndpoint, aps_frame.clusterId, message)
  File "/usr/local/lib/python3.7/site-packages/zigpy/application.py", line 74, in deserialize
    return sender.deserialize(endpoint_id, cluster_id, data)
  File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 98, in deserialize
    return self.endpoints[endpoint_id].deserialize(cluster_id, data)
KeyError: 1
2019-03-17 11:37:38 ERROR (MainThread) [bellows.ezsp] Exception running handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bellows/ezsp.py", line 194, in handle_callback
    handler(*args)
  File "/usr/local/lib/python3.7/site-packages/bellows/zigbee/application.py", line 160, in ezsp_callback_handler
    self._handle_frame(*args)
  File "/usr/local/lib/python3.7/site-packages/bellows/zigbee/application.py", line 181, in _handle_frame
    tsn, command_id, is_reply, args = self.deserialize(device, aps_frame.sourceEndpoint, aps_frame.clusterId, message)
  File "/usr/local/lib/python3.7/site-packages/zigpy/application.py", line 74, in deserialize
    return sender.deserialize(endpoint_id, cluster_id, data)
  File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 98, in deserialize
    return self.endpoints[endpoint_id].deserialize(cluster_id, data)
KeyError: 1
2019-03-17 11:37:39 ERROR (MainThread) [bellows.ezsp] Exception running handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bellows/ezsp.py", line 194, in handle_callback
    handler(*args)
  File "/usr/local/lib/python3.7/site-packages/bellows/zigbee/application.py", line 160, in ezsp_callback_handler
    self._handle_frame(*args)
  File "/usr/local/lib/python3.7/site-packages/bellows/zigbee/application.py", line 181, in _handle_frame
    tsn, command_id, is_reply, args = self.deserialize(device, aps_frame.sourceEndpoint, aps_frame.clusterId, message)
  File "/usr/local/lib/python3.7/site-packages/zigpy/application.py", line 74, in deserialize
    return sender.deserialize(endpoint_id, cluster_id, data)
  File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 98, in deserialize
    return self.endpoints[endpoint_id].deserialize(cluster_id, data)
KeyError: 1
2019-03-17 11:37:45 WARNING (MainThread) [bellows.zigbee.application] Unexpected response TSN=0 command=266 args=b'\x00\x00),\n'
2019-03-17 11:37:45 WARNING (MainThread) [zigpy.endpoint] [0x261d:1] Message on unknown cluster 0x0402
2019-03-17 11:37:45 WARNING (MainThread) [bellows.zigbee.application] Unexpected response TSN=1 command=266 args=b'\x00\x00!\xf8$'
2019-03-17 11:37:45 WARNING (MainThread) [zigpy.endpoint] [0x261d:1] Message on unknown cluster 0x0405
2019-03-17 11:37:50 DEBUG (MainThread) [homeassistant.components.zha.core.device] LUMI lumi.sens: started configuration
2019-03-17 11:37:51 DEBUG (MainThread) [homeassistant.components.zha.core.channels] node descriptor: [<Status.SUCCESS: 0>, 9757, <NodeDescriptor byte1=2 byte2=64 mac_capability_flags=128 manufacturer_code=4151 maximum_buffer_size=127 maximum_incoming_transfer_size=100 server_mask=0 maximum_outgoing_transfer_size=100 descriptor_capability_field=0>]
2019-03-17 11:37:51 DEBUG (MainThread) [homeassistant.components.zha.core.device] LUMI lumi.sens: channel: zdo-LUMI lumi.sens_ZDO async_configure stage succeeded
2019-03-17 11:37:51 DEBUG (MainThread) [homeassistant.components.zha.core.channels] 0x261d:1:0x0000: finished channel configuration
2019-03-17 11:37:53 DEBUG (MainThread) [homeassistant.components.zha.core.device] LUMI lumi.sens: channel: basic-0x261d:1:0x0000 async_configure stage succeeded
2019-03-17 11:37:53 DEBUG (MainThread) [homeassistant.components.zha.core.helpers] 0x261d:3:0x000c: bound  'analog_input' cluster: Status.SUCCESS
2019-03-17 11:37:53 ERROR (MainThread) [zigpy.zcl] [0x261d:3:0x000c] 0 is not a valid attribute id
2019-03-17 11:37:53 WARNING (MainThread) [homeassistant.components.zha.core.device] LUMI lumi.sens channel: attribute-0x261d:3:0x000c async_configure stage failed ex: object NoneType can't be used in 'await' expression
2019-03-17 11:37:53 DEBUG (MainThread) [homeassistant.components.zha.core.device] LUMI lumi.sens: completed configuration
2019-03-17 11:37:53 DEBUG (MainThread) [homeassistant.components.zha.core.device] LUMI lumi.sens: stored in registry: ZhaDeviceEntry(name='LUMI lumi.sens', ieee='00:15:8d:00:01:59:79:69', power_source=0, manufacturer_code=4151, last_seen=1552819073.2721326)
2019-03-17 11:37:53 DEBUG (MainThread) [homeassistant.components.zha.core.device] LUMI lumi.sens: started initialization
2019-03-17 11:37:53 DEBUG (MainThread) [homeassistant.components.zha.core.channels] entry loaded from storage: ZhaDeviceEntry(name='LUMI lumi.sens', ieee='00:15:8d:00:01:59:79:69', power_source=0, manufacturer_code=4151, last_seen=1552819073.2721326)
2019-03-17 11:37:53 DEBUG (MainThread) [homeassistant.components.zha.core.device] LUMI lumi.sens: channel: zdo-LUMI lumi.sens_ZDO async_initialize stage succeeded
2019-03-17 11:37:53 WARNING (MainThread) [bellows.zigbee.application] Unexpected response TSN=0 command=266 args=b'\x00\x00)D\n'
2019-03-17 11:37:53 WARNING (MainThread) [zigpy.endpoint] [0x261d:1] Message on unknown cluster 0x0402
2019-03-17 11:37:53 WARNING (MainThread) [bellows.zigbee.application] Unexpected response TSN=1 command=266 args=b'\x00\x00!&%'
2019-03-17 11:37:53 WARNING (MainThread) [zigpy.endpoint] [0x261d:1] Message on unknown cluster 0x0405
2019-03-17 11:37:58 DEBUG (MainThread) [homeassistant.components.zha.core.device] LUMI lumi.sens: channel: basic-0x261d:1:0x0000 async_initialize stage succeeded
2019-03-17 11:37:58 DEBUG (MainThread) [homeassistant.components.zha.core.device] LUMI lumi.sens: channel: attribute-0x261d:3:0x000c async_initialize stage succeeded
2019-03-17 11:37:58 DEBUG (MainThread) [homeassistant.components.zha.core.device] LUMI lumi.sens: power source: Battery or Unknown
2019-03-17 11:37:58 DEBUG (MainThread) [homeassistant.components.zha.core.device] LUMI lumi.sens: completed initialization
2019-03-17 11:37:58 WARNING (MainThread) [bellows.zigbee.application] Unexpected response TSN=61 command=1 args=[[<ReadAttributeRecord attrid=0 status=134>]]
2019-03-17 11:37:59 WARNING (MainThread) [bellows.zigbee.application] Unexpected response TSN=60 command=1 args=[[<ReadAttributeRecord attrid=7 status=0 value=3>]]
2019-03-17 11:37:59 WARNING (MainThread) [bellows.zigbee.application] Unexpected response TSN=61 command=1 args=[[<ReadAttributeRecord attrid=0 status=134>]]
2019-03-17 11:37:59 WARNING (MainThread) [bellows.zigbee.application] Unexpected response TSN=0 command=266 args=b'\x00\x00)N\n'
2019-03-17 11:37:59 WARNING (MainThread) [zigpy.endpoint] [0x261d:1] Message on unknown cluster 0x0402
2019-03-17 11:37:59 WARNING (MainThread) [bellows.zigbee.application] Unexpected response TSN=1 command=266 args=b'\x00\x00!7%'
2019-03-17 11:37:59 WARNING (MainThread) [zigpy.endpoint] [0x261d:1] Message on unknown cluster 0x0405
2019-03-17 11:38:00 WARNING (MainThread) [bellows.zigbee.application] Unexpected response TSN=60 command=1 args=[[<ReadAttributeRecord attrid=7 status=0 value=3>]]
2019-03-17 11:38:01 WARNING (MainThread) [bellows.zigbee.application] Unexpected response TSN=0 command=266 args=b'\x00\x00)T\n'
2019-03-17 11:38:01 WARNING (MainThread) [zigpy.endpoint] [0x261d:1] Message on unknown cluster 0x0402
2019-03-17 11:38:01 WARNING (MainThread) [bellows.zigbee.application] Unexpected response TSN=1 command=266 args=b'\x00\x00!@%'
2019-03-17 11:38:01 WARNING (MainThread) [zigpy.endpoint] [0x261d:1] Message on unknown cluster 0x0405
```

**Comment by Adminiuga** [comment] 2019-05-05 02:53
There are a few issues at play here:
1. First of all, either this is an incomplete log or the device was already joined previously (not saying it was discovered successfully on previous join), as I don't see any "device joined" messages
2. it is normal to see `KeyError: 1` with xiaomi when then just joined and HA has not finished device discovery, as xiaomi keeps sending attribute 
3.  IMO there was a problem with Mija quirks which was fixed in https://github.com/dmulcahey/zha-device-handlers/pull/68 

Wait till new version of `zha-device-handlers` (`zha-quirks`) gets released. Remove that sensor from HA assistant (both from ZHA config panel) and try joining it again. Keep pressing the button once ever 1.5s to keep the device awake while it is being discovered/configured by ZHA component.

Other than that the problem is not in `bellows` so I'm gonna close it for now.

**Closed** 2019-05-23 22:37 UTC
